### ISSUE TITLE
Python Filter nötig?

### ISSUE THREAD

**Issue by luebby** [FOM-ifes/DA-R-Cheatsheet#4]
Wenn wir das - was wir meiner Meinung nach machen sollten - verbreiten wollten: brauchen wir hier den zusätzlichen (in der Tat tollen!) Zusatz über den Typographie Filter? Sprich, lohnt sich der Aufwand für die Anwender*innen?

**Comment by NMarkgraf** [comment]
Ja! - Vor allem, weil der Pyhton-Filter bald durch einen Lua-Filter ersetzt werden wird/kann. Dann ist die Installation von Pyhton nicht mehr nötig. Denn Lua-Filter sind native Freunde von pandoc. 
;-) -- Und ganz ehrlich. OHNE den Filter sieht es bei weitem nicht mehr so toll aus. ;-)

**Comment by NMarkgraf** [comment]
OH JE,

was für eine Ankündigung! - "bald" -- Okay, die Updates auf Lua hat es (leider) nicht gegeben. Dafür ist das "Schatzkästchen" nun nach FOM-ifes umgezogen.

Viele Grüße
Norman Markgraf
